CREATE OR REPLACE USER dbt_shrestic PASSWORD='password';
GRANT ROLE TRANSFORMER_DEV TO USER dbt_shrestic;


CREATE OR REPLACE USER loader_adam PASSWORD='password';
GRANT ROLE LOADER_DEV TO USER loader_adam;

CREATE OR REPLACE USER CI_USER PASSWORD = 'password';
CREATE OR REPLACE ROLE CI_ROLE COMMENT = 'This role is use for CI/CD operations';
GRANT ROLE CI_ROLE TO USER CI_USER;

GRANT ROLE LOADER_PROD,LOADER_PREPROD, LOADER_DEV,TRANSFORMER_DEV,TRANSFORMER_PREPROD,TRANSFORMER_PROD TO ROLE CI_ROLE;

SHOW GRANTS TO ROLE CI_ROLE;
